### ISSUE TITLE
Function onERC721Received will be called twice

### ISSUE THREAD

**Issue by yuriy77k** [Dexaran/CallistoNFT#4]
The function  onERC721Received will be called twice in the receiver contract if use 'safe' transfers. It may cause unpredictable issues.

Function [_safeTransfer](https://github.com/Dexaran/CallistoNFT/blob/a886f3bb0321c5100fd193ee94363bc60d625b5d/ERC721Compatible/ERC721CallistoNFTHybrid.sol#L531-L541) calls [_transfer](https://github.com/Dexaran/CallistoNFT/blob/a886f3bb0321c5100fd193ee94363bc60d625b5d/ERC721Compatible/ERC721CallistoNFTHybrid.sol#L790-L822) with empty `data`  and then calls `_checkOnERC721Received` with data passed in parameter. 
But both functions `_transfer` and `_checkOnERC721Received` calls `onERC721Received` in receiver contract.

Recommendation: remove parameter `data` and this part: https://github.com/Dexaran/CallistoNFT/blob/a886f3bb0321c5100fd193ee94363bc60d625b5d/ERC721Compatible/ERC721CallistoNFTHybrid.sol#L816-L819
from `_transfer` function. 
And use `_safeTransfer` instead of `_transfer` wherever need to transfer a token with the receiver checker.
But I think the ERC721 has two types of transfer functions to check the receiver in `safe` transfer and don't check it in standard transfer. Maybe will be needed to transfer the NFT token to multisig wallet that hasn't `onERC721Received` function implemented.

**Comment by Dexaran** [comment]
Changed.

https://github.com/Dexaran/CallistoNFT/blob/00cf1ce00fb8810bd5276b2a4758278ef07a8981/ERC721Compatible/ERC721CallistoNFTHybrid.sol#L821-L824


https://github.com/Dexaran/CallistoNFT/blob/00cf1ce00fb8810bd5276b2a4758278ef07a8981/ERC721Compatible/ERC721CallistoNFTHybrid.sol#L703-L708


https://github.com/Dexaran/CallistoNFT/blob/00cf1ce00fb8810bd5276b2a4758278ef07a8981/ERC721Compatible/ERC721CallistoNFTHybrid.sol#L368-L386

`_transfer` does not call the `onERC721Received` anymore.

All uses of `_transfer` are now replaced with `_safeTransfer(...)` invocations which calls both `try _checkOnERC721Received(...)` and `_transfer` under the hood.

However ERC721 `_checkOnERC721Received` requires a specified return value from this function while CallistoNFT requires that the transfer simply not fail or get rejected.

Now all transfers are relying on ERC721-like behavior for optimization reasons to avoid bloating the contract and increasing deployment GAS usage
